### ISSUE TITLE
Zeitbeschränkung bei Sondererlaubnis für einzelne Arbeiten

### ISSUE THREAD

**Issue by Virtex7** [fau-fablab/drehbank-einweisung#6]
gleiche Frage wie bei "Zeitbeschränkung bei Einweisung", welche Begründung steht auch hier hinter der extrem kurzen Zeit. Diese steht in keinem Verhältnis zum Einweisungsaufwand.

**Comment by mgmax** [comment]
Sonst könnte man gleich den Leuten die jeweilige Einweisungsstufe erteilen... Mit größerem Risiko sollte auch eine häufigere Erneuerung einhergehen, so die Intention.
